# azure-pipelines.yml
trigger: none

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
    default: "uat"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "constant"
      - "load"
      - "spike"
      - "stress"
    default: "constant"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - receipt_generator
  - name: "DB_NAME"
    displayName: "DB name"
    type: string
    values:
      - pagopa_receipt_pdf_generatork6

variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    receiptQueueSubscriptionKey: "$(DEV_RECEIPT_QUEUE_SUBSCRIPTION_KEY)"
    receiptCosmosSubscriptionKey: "$(DEV_RECEIPT_COSMOS_DB_SUBSCRIPTION_KEY)"
    poolImage: 'pagopa-dev-loadtest-linux'
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    receiptQueueSubscriptionKey: "$(UAT_RECEIPT_QUEUE_SUBSCRIPTION_KEY)"
    receiptCosmosSubscriptionKey: "$(UAT_RECEIPT_COSMOS_DB_SUBSCRIPTION_KEY)"
    poolImage: 'pagopa-uat-loadtest-linux'

pool:
  name: $(poolImage)

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image
  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh ${{ parameters.ENVIRONMENT }} ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} ${{ parameters.DB_NAME }} $RECEIPT_QUEUE_SUBSCRIPTION_KEY $RECEIPT_COSMOS_SUBSCRIPTION_KEY
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
    env:
      RECEIPT_QUEUE_SUBSCRIPTION_KEY: ${{ variables.receiptQueueSubscriptionKey }}
      RECEIPT_COSMOS_SUBSCRIPTION_KEY: ${{ variables.receiptCosmosSubscriptionKey }}
      