package it.gov.pagopa.receipt.pdf.generator.service;

import it.gov.pagopa.receipt.pdf.generator.exception.SavePDFToBlobException;
import it.gov.pagopa.receipt.pdf.generator.model.PdfMetadata;
import it.gov.pagopa.receipt.pdf.generator.model.response.PdfEngineResponse;

public interface ReceiptBlobStorageService {

    /**
     * Saves the PDF generated by PDF Engine in receipt storage with the provided name
     *
     * @param pdfEngineResponse PDF Engine response that contains the reference to the generated PDF
     * @param blobName          name of the blob
     * @return the metadata with the reference to the saved blob
     * @throws SavePDFToBlobException when an error occur while saving the PDF
     */
    PdfMetadata saveToBlobStorage(PdfEngineResponse pdfEngineResponse, String blobName) throws SavePDFToBlobException;
}
