microservice-chart:
  namespace: "receipts"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-receipt-pdf-generator
    tag: "1.11.5"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weudev.receipts.internal.dev.platform.pagopa.it"
    path: /pagopa-receipt-pdf-generator/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1512Mi"
      cpu: "0.75"
    limits:
      memory: "1512Mi"
      cpu: "0.75"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    TZ: "Europe/Rome"
    ENV: "dev"
    WEBSITE_SITE_NAME: "pagopareceiptpdfgenerator" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    RECEIPT_QUEUE_TOPIC: "pagopa-d-weu-receipts-queue-receipt-waiting-4-gen"
    RECEIPT_QUEUE_TOPIC_POISON: "pagopa-d-weu-receipts-queue-receipt-waiting-4-gen-poison"
    COSMOS_RECEIPT_QUEUE_MAX_RETRY: "5"
    PDF_ENGINE_ENDPOINT: "https://api.dev.platform.pagopa.it/shared/pdf-engine/v1/generate-pdf"
    COSMOS_RECEIPT_SERVICE_ENDPOINT: "https://pagopa-d-weu-receipts-ds-cosmos-account.documents.azure.com:443/"
    COSMOS_RECEIPT_DB_NAME: "db"
    COSMOS_RECEIPT_CONTAINER_NAME: "receipts"
    BLOB_STORAGE_ACCOUNT_ENDPOINT: "https://pagopadweureceiptsfnsa.blob.core.windows.net/"
    BLOB_STORAGE_CONTAINER_NAME: "pagopa-d-weu-receipts-azure-blob-receipt-st-attach"
    WORKING_DIRECTORY_PATH: "/temp"
    MIN_PDF_LENGTH: "10000"
    PDV_TOKENIZER_BASE_PATH: "https://api.uat.tokenizer.pdv.pagopa.it/tokenizer/v1"
    ENABLE_ECS_CONSOLE: "true"
    CONSOLE_LOG_THRESHOLD: "DEBUG"
    CONSOLE_LOG_PATTERN: "%d{HH:mm:ss.SSS}[%thread]%-5level%logger{36}-%msg%n"
    CONSOLE_LOG_CHARSET: "UTF-8"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopareceiptpdfgeneratorotl,deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    AZURE_FUNCTIONS_MESH_JAVA_OPTS: "-javaagent:/home/site/wwwroot/jmx_prometheus_javaagent-0.19.0.jar=12345:/home/site/wwwroot/config.yaml -javaagent:/home/site/wwwroot/opentelemetry-javaagent.jar -Xmx1024m -XX:+UseG1GC"
  envConfigMapExternals:
    template-maps:
      BRAND_LOGO_MAP: brand-logo-map
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-d-connection-string"
    RECEIPTS_STORAGE_CONN_STRING: "receipts-storage-account-connection-string"
    COSMOS_RECEIPTS_CONN_STRING: "cosmos-receipt-connection-string"
    OCP_APIM_SUBSCRIPTION_KEY: "shared-apim-d-subscription-key"
    COSMOS_RECEIPT_KEY: "cosmos-receipt-pkey"
    OTEL_EXPORTER_OTLP_HEADERS: 'elastic-otl-secret-token'
    PDV_TOKENIZER_SUBSCRIPTION_KEY: "tokenizer-api-key"
    AES_SECRET_KEY: "aes-secret-key"
    AES_SALT: "aes-salt"
  keyvault:
    name: "pagopa-d-receipts-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: false
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: false
    deployment:
      create: false
      image:
        repository: ghcr.io/pagopa/pagopa-receipt-pdf-generator
        tag: "1.0.2"
        pullPolicy: Always
      envConfig:
      envSecret:
